/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fss_server;

import org.junit.jupiter.api.Test;

import fss_server.entities.User;
import fss_server.file_access.UserData;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void addUser() {
        UserData userData = new UserData();
        userData.addUser(new User("kjy", "001"));
        userData.addUser(new User("hsy", "002"));
    }
}
